version: "3.1"

services:
  db:
    build:
      context: ./db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/90.test.sql:/docker-entrypoint-initdb.d/90.test.sql:ro
  postgraphile:
    build:
      context: ./postgraphile
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db"
      JWT_SECRET: "superSecretKey"
    ports:
      - 4000:4000
  pgadmin:
    image: dpage/pgadmin4:4.29
    restart: unless-stopped
    user: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin"
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - "./pgadmin/servers.json:/pgadmin4/servers.json"
      # To save passwords, think to run `sudo chown -R 5050:5050 pgadmin/pgadmin4.db`
      - "./pgadmin/pgadmin4.db:/var/lib/pgadmin/pgadmin4.db:rw"
    ports:
      - 8081:80
