apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: messages
build:
  artifacts:
  - image: messages-db
    context: db
    docker:
      dockerfile: Dockerfile
  - image: postgraphile
    context: postgraphile
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
