apiVersion: v1
kind: Service
metadata:
  name: messages-db
spec:
  ports:
  - port: 5432
    nodePort: 32101
  type: NodePort
  selector:
    app: messages-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-db
spec:
  selector:
    matchLabels:
      app: messages-db
  template:
    metadata:
      labels:
        app: messages-db
    spec:
      containers:
      - name: messages-db
        image: messages-db
        env:
          - name : POSTGRES_PASSWORD
            value: postgres
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

